# Generated by Django 5.0.6 on 2024-07-19 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contactnumber',
            field=models.BigIntegerField(),
        ),
    ]
