# Generated by Django 5.0.6 on 2024-06-27 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_contactnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contactnumber',
            field=models.CharField(max_length=10),
        ),
    ]
