# Generated by Django 5.0.6 on 2024-07-19 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_contactnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contactnumber',
            field=models.BigIntegerField(),
        ),
    ]
